# Generated by Django 3.2 on 2021-07-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=50)),
                ('Title_of_the_story', models.CharField(max_length=200)),
                ('Date', models.DateField(auto_now=True)),
                ('Story_Description', models.TextField(null=True)),
                ('Image', models.ImageField(default='', upload_to='story/')),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
