# Generated by Django 3.2 on 2021-07-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0002_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='Story_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='Your_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='Title_of_the_story',
            new_name='Title',
        ),
    ]
