# Generated by Django 3.2 on 2021-07-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0003_auto_20210711_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='Name',
            new_name='Your_Name',
        ),
    ]
