# Generated by Django 3.2 on 2021-07-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0004_rename_name_upload_your_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='Your_Name',
            new_name='Name',
        ),
    ]
