# Generated by Django 3.2 on 2021-07-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0005_rename_your_name_upload_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=200)),
                ('Date', models.DateField(auto_now=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
    ]
